train:
  batch_size_per_gpu: 64
  data_min_axis_size: 48
  OFFICIAL_EPOCH_LENGTH: 125
student:
  full_pretrained_weights: '/home/jovyan/shared/pedro-maciasgordaliza/fomo25/JEPA3d_last-models/3D-JEPA/128_target_encoder_checkpoint.pth'
crops:
  global_crops_size: 128
  local_crops_size: 64
optim:
  base_lr: 0.001
evaluation:
  eval_period_iterations: 3125
