MODEL:
  WEIGHTS: ''
compute_precision:
  grad_scaler: true
  target_encoder:
    sharding_strategy: SHARD_GRAD_OP
    mixed_precision:
      param_dtype: fp16
      reduce_dtype: fp16
      buffer_dtype: fp32
  encoder:
    sharding_strategy: SHARD_GRAD_OP
    mixed_precision:
      param_dtype: fp16
      reduce_dtype: fp16
      buffer_dtype: fp32
  predictor:
    sharding_strategy: SHARD_GRAD_OP
    mixed_precision:
      param_dtype: fp16
      reduce_dtype: fp16
      buffer_dtype: fp32
train:
  batch_size_per_gpu: 128 # 128
  data_min_axis_size: 24
  dataset_path:  "/Benson_DATA2/gerinb/FOMO2025/FOMO-MRI-preprocessed/dataset.json" #'/Benson_DATA2/gerinb/FOMO2025/FOMO-MRI-preprocessed/dataset.json' #"/Benson_DATA2/gerinb/FOMO2025/FOMO-MRI-preprocessed/dataset_first_100.json" # '/Benson_DATA2/gerinb/FOMO2025/FOMO-MRI-preprocessed/dataset.json'
  output_dir: ./output_test
  saveckp_freq: 1
  seed: 0
  num_workers: 20
  OFFICIAL_EPOCH_LENGTH: 1280 # 1280
  cache_dataset: True
  centering: sinkhorn_knopp
encoder:
  arch: vit_large_3d
  patch_size: 16
  drop_path_rate: 0.3
  layerscale: 1.0e-05
  drop_path_uniform: true
  pretrained_weights: ''
  full_pretrained_weights: ''
  ffn_layer: "mlp"
  block_chunks: 4
  qkv_bias: true
  proj_bias: true
  ffn_bias: true
  pred_embed_dim: 384
  pred_depth: 12
optim:
  epochs: 100
  weight_decay: 0.04
  weight_decay_end: 0.4
  base_lr: 0.002  # 0.002 learning rate for a batch size of 1024
  lr: 0.  # will be set after applying scaling rule
  warmup_epochs: 10
  start_lr: 1.0e-06 # 1.0e-06
  min_lr: 1.0e-06
  clip_grad: 3.0 # 3.0
  scaling_rule: sqrt_wrt_1024
  patch_embed_lr_mult: 0.0
  layerwise_decay: 0.9
  adamw_beta1: 0.9
  adamw_beta2: 0.999
target_encoder:
  ema_start: 0.996 # 0.996
  ema_end: 1.0
input:
  size: 96
  pred_mask_scale:
  - 0.03
  - 0.2
  enc_mask_scale:
  - 0.4
  - 1.0
  aspect_ratio:
  - 0.33333
  - 3.0
  depth_ratio:
  - 0.333333
  - 3.0
  num_enc_masks: 1
  num_pred_masks: 4
  allow_overlap: False
  allow_overlap_prob: 0.2
  min_keep: 0
crops:
  global_crops_in_slice_scale:
  - 0.48
  - 1.0
  global_crops_cross_slice_scale:
  - 0.5
  - 1.0
  global_crops_size: 96
evaluation:
  eval_period_iterations: 12800
